import { renderTemplate } from '@/data/templates';

export function contentFor(node, ctx) {
  const c = renderTemplate(node.template, { ...ctx, deps: node.deps || ctx.deps });
  return c;
}

export function generateScript(tree, projectName, projectType) {
  const lines = [
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    '# Generated by Rustruct. Creates the project structure and writes',
    '# starter files. Safe to read top to bottom before running.',
    `# Project: ${projectName}  (${projectType})`,
    '',
    `mkdir -p "${projectName}"`,
    `cd "${projectName}"`,
    '',
  ];
  const dirs = [];
  const files = [];

  function walk(node, path, crateName) {
    if (!node.children) return;
    for (const child of node.children) {
      const childPath = path ? `${path}/${child.name}` : child.name;
      let cName = crateName;
      if (child.type === 'folder') {
        dirs.push(childPath);
        if (path === 'crates') cName = child.name; // direct child of crates/ is a crate root
        walk(child, childPath, cName);
      } else {
        files.push({ path: childPath, content: contentFor(child, { projectName, projectType, crateName: cName, deps: child.deps }) });
      }
    }
  }
  walk(tree, '', null);

  if (dirs.length) {
    lines.push('# --- directories ---');
    dirs.forEach(d => lines.push(`mkdir -p "${d}"`));
    lines.push('');
  }
  if (files.length) {
    lines.push('# --- files ---');
    files.forEach(f => {
      if (f.content != null) {
        // Quoted heredoc terminator ('EOF') prevents shell expansion of file
        // contents, so $ and backticks in the Rust code stay literal.
        lines.push(`cat > "${f.path}" << 'RUSTRUCT_EOF'`);
        lines.push(f.content.replace(/\n$/, ''));
        lines.push('RUSTRUCT_EOF');
      } else {
        lines.push(`touch "${f.path}"`);
      }
    });
    lines.push('');
  }
  lines.push('echo "Done. Next: cargo build"');
  return lines.join('\n');
}
